export {};

declare global {
  type LkFontClass =
    | "display1"
    | "display2"
    | "title1"
    | "title2"
    | "title3"
    | "heading"
    | "subheading"
    | "body"
    | "callout"
    | "label"
    | "caption"
    | "capline"
    | "display1-bold"
    | "display2-bold"
    | "title1-bold"
    | "title2-bold"
    | "title3-bold"
    | "heading-bold"
    | "subheading-bold"
    | "body-bold"
    | "callout-bold"
    | "label-bold"
    | "caption-bold"
    | "capline-bold"
    | "display1-mono"
    | "display2-mono"
    | "title1-mono"
    | "title2-mono"
    | "title3-mono"
    | "heading-mono"
    | "subheading-mono"
    | "body-mono"
    | "callout-mono"
    | "label-mono"
    | "caption-mono"
    | "capline-mono";
}
